[versions]
agp = "8.2.0"
kotlin = "1.9.21"
coreKtx = "1.12.0"
appcompat = "1.6.1"
material = "1.11.0"
constraintlayout = "2.1.4"
lifecycle = "2.7.0"
activityKtx = "1.8.2"
fragmentKtx = "1.6.2"
recyclerview = "1.3.2"

# Compiler tools
ecj = "3.38.0"
r8 = "8.3.37"
baksmali = "2.5.2"
dexlib2 = "2.5.2"

# Editor
soraEditor = "0.23.4"

# Testing
junit = "4.13.2"
junitExt = "1.1.5"
espressoCore = "3.5.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

# Compiler tools
ecj = { group = "org.eclipse.jdt", name = "ecj", version.ref = "ecj" }
r8 = { group = "com.android.tools", name = "r8", version.ref = "r8" }
baksmali = { group = "org.smali", name = "baksmali", version.ref = "baksmali" }
dexlib2 = { group = "org.smali", name = "dexlib2", version.ref = "dexlib2" }
janino = { group = "org.codehaus.janino", name = "janino", version = "3.1.12" }
asm = { group = "org.ow2.asm", name = "asm", version = "9.7.1" }

# Editor
sora-editor = { group = "io.github.Rosemoe.sora-editor", name = "editor", version.ref = "soraEditor" }
sora-language-java = { group = "io.github.Rosemoe.sora-editor", name = "language-java", version.ref = "soraEditor" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
